version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mrkstechs
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
volumes:
  db_data: